import './globals.css'
import type { Metadata } from 'next'
import Navbar from './nav/Navbar'

export const metadata: Metadata = {
  title: 'Carios',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className='container mx-auto px-4 sm:px-6 md:px-8 lg:px-10 xl:px-20 pt-20'>
          {children}
        </main>
      </body>
    </html>
  )
}
